### ISSUE TITLE
Space bar in private message body doesn’t work via Bluetooth keyboard for iPad Pro landscape mode

### ISSUE THREAD

**Issue by dz314159** [christianselig/apollo-bugs#340] opened 2019-09-21 02:03 UTC
**Describe the bug**

Space bar in private message body doesn’t work via Bluetooth keyboard for iPad Pro landscape mode

**To Reproduce**

0. Use USB keyboard on iPad Pro in landscape mode
1. Click someone’s username
2. Click Private Message
3. Type “Foo Bar” in message title - no issue
4. Type “Foo Bar” in message body, space does not appear at all

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
12.4.1

**Apollo version**: Version of Apollo this bug occurred on (can be found in Apollo's Settings tab > About)
1.6

**iOS device**: For example iPhone XS, iPad mini, etc.
iPad Pro

**Jailbroken**: Whether or not your device is jailbroken
Nope

**Reproducible:** Can you reproduce it every time? Or is it random?
Yes

**Expected behavior**
Expected: space bar input works as designed.  :-)

**Screenshots**
If possible, add screenshots to help show the problem.
N/A

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.
N/A

**Additional context**
N/A

**Comment by cfdelwiche** [comment] 2019-09-21 16:25
I have this same issue using an iPad Pro 10” in landscape mode. It seemed to appear at the last version update (last night on my device). The problem does not occur in other apps, nor does it occur if I use the onscreen keyboard.

However, the keyboard I am using is not a bluetooth keyboard, but rather the Apple case/keyboard combo that connects via three contacts on the back of the iPad. I just verified that it is bluetooth independent by turning off bluetooth and the keyboard still functions. 

Thanks for a great app.

**Comment by MaxHasADHD** [comment] 2019-09-21 19:06
This is happening for me as well with the 12.9" iPad Pro and Apple Smart Keyboard. I think another view of the app is capturing the space bar

**Comment by MaxHasADHD** [comment] 2019-09-21 19:10
This happens everywhere in the app for me though not just messages. I can't comment or post with spaces anymore.

**Comment by chardelwi** [comment] 2019-09-21 20:45
Yes, everywhere in the app. At first I thought my keyboard had failed.

**Comment by pagrossi91** [comment] 2019-09-22 03:21
Same issue for me but I noticed it commenting.  It seems independent of orientation.  The arrow keys are also inoperable on my Bluetooth keyboard. I'm running the iOS 13.1 Dev Build 17A5844a.  My keyboard is the Zagg Slim Book Go.

**Comment by bkx3** [comment] 2019-09-22 03:31
Same issue with the Smart Keyboard and a standard keyboard connected over USB, anywhere in the app. Space bar works perfectly with the software keyboard and in other apps. 

This is in the latest version of Apollo, running 13.1 on an iPad Pro.

**Comment by brandoncordell** [comment] 2019-09-22 14:54
Same issue running iPadOS 13.1 public beta 4, iPad Pro 11” using the Apple Folio Keyboard. The spacebar doesn’t work inside any text boxes but when I attempt to use the spacebar in the search bar at the top of the Posts tab it actually scrolls the feed 4-5 posts at a time (similar to hitting space bar on a webpage in Chrome).

**Comment by grahamj** [comment] 2019-09-23 13:11
Same, iPad Pro 10.5”, iOS 12.4.1, Apollo 1.6, Bluetooth keyboard, landscape mode. Space bar not working in comment reply. 

I recorded a video of it happening in case it’s wanted.

**Comment by ghost** [comment] 2019-09-23 15:23
Space and enter do not work with smart keyboard.

**Comment by grahamj** [comment] 2019-09-23 18:12
This looks to be a duplicate of https://github.com/christianselig/apollo-bugs/issues/333

**Comment by grahamj** [comment] 2019-09-25 13:03
I found a workaround: hold the Option key while pressing space. But clearly @christianselig needs to address this soon. I would call it gating.

**Comment by brandoncordell** [comment] 2019-09-25 13:19
Holding Option works for me too but it's a pain in the butt enough to make me use the official Reddit app for now.

**Comment by grahamj** [comment] 2019-09-25 13:19
Ya it's not fun for sure.

**Comment by chardelwi** [comment] 2019-09-25 14:48
Great catch @grahamj! This works on my 11" iPad Pro & Smart Keyboard as well. This is super annoying, but if you type mindfully it can help. I upgraded to iPadOS 13.1 last night, but it did not resolve the problem.

**Comment by christianselig** [comment] 2019-09-29 21:21
Fixed

**Closed as completed by christianselig** 2019-09-29 21:21 UTC
Labels: bug

**Comment by grahamj** [comment] 2019-09-29 23:19
Thanks!
  

  
  

  
  
>
