### ISSUE TITLE
Apollo quits completely on opening a post

### ISSUE THREAD

**Issue by forcedmeme** [christianselig/apollo-bugs#1911] opened 2022-11-01 08:30 UTC
I have had this bug since updating to MacOs 13.0. Any post will crash the app if you open it's comments. You can open a picture post, or a link, but if you open the comment thread of that post, the app will crash immediately.

App version: 1.14.8
ios version: MacOs 13.0
Device Type: Macbook air m2
How often can you reproduce the issue: 100%
Reproducible Steps: Open comments on any post, app crashes immediately. Pictures can open, but opening the comments on a picture thread crashes the app.

**Comment by jaywelch** [comment] 2022-11-01 17:43
Duplicate of #1904.

**Comment by forcedmeme** [comment] 2022-11-01 17:45
Closing because it's a duplicate of #1904

**Closed as completed** 2022-11-01 17:45 UTC
