### ISSUE TITLE
Long pressing on the Jump Button to jump up to the previous top level comment fails, if the current comment is deleted or removed.

### ISSUE THREAD

**Issue by randallbruder** [christianselig/apollo-bugs#712] opened 2020-05-12 01:39 UTC
**Describe the bug**
Long pressing on the Jump Button to jump up to the previous top level comment fails, if the current comment is deleted or removed.

**To Reproduce**
1. Pick any popular post (one that is likely to have a top-level comment deleted or removed.)
2. Use the jump button to drop down to a deleted/removed comment, and even past it.
3. Long press on the jump button to jump up one parent comment.
4. When jumping up to a deleted/removed comment, long pressing on the jump button has no effect.

**iOS version**: iOS 13.4.1
**Apollo version**: 1.8 (52)
**iOS device:** iPhone 11 Pro
**Jailbroken**: No
**Reproducible:** Every time

**Expected behavior**
Long pressing on the jump button while on a deleted/removed comment should still jump you up to the previous parent comment, instead of doing nothing.

**Video**
https://streamable.com/4oyzp

**Comment by jorwex** [comment] 2020-09-18 02:19
Believe this is a duplicate of #686.

**Comment by randallbruder** [comment] 2020-09-18 03:00
Yep, it's a duplicate

**Closed as completed** 2020-09-18 03:00 UTC
Labels: bug
