### ISSUE TITLE
Tapping on PURER Black Dark Mode causes app to crash

### ISSUE THREAD

**Issue by codywilliamson** [christianselig/apollo-bugs#1557] opened 2021-12-28 06:48 UTC
OS: iOS 15.2
Device: iPhone 12 Pro
App Version: Apollo 1.12

When simply tapping on the PURER Black Dark Mode label, it causes the application to crash. When toggling the option, everything seems to work as normal.

**Comment by fordan** [comment] 2022-09-09 20:41
Also seeing this.

OS: iOS 15.6.1
Device: iPhone 13 Pro
App Version: 1.13.1

**Comment by ThomasAllan** [comment] 2022-09-17 19:12
This is a duplicate of #499

**Closed as not planned** 2022-11-01 19:27 UTC
